language: csharp
solution: src/KeePassWinHello.sln

addons:
  apt:
    packages:
      - openjdk-8-jdk
      - npm
  sonarcloud:
    organization: "sirandros-github"

jdk:
  - oraclejdk8

script:
  - sonar-scanner
  - npm install -g snyk
  - snyk test

cache:
  directories:
    - '$HOME/.sonar/cache'
